Vagrant.configure("2") do |config|
  # We use Ubuntu 12.04 LTS (Precise Pangolin) as our box. This was the only
  # stable box that worked in all our environments. We use 13.04 (Raring
  # Ringtail) repository sources in Puppet though.
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Map port 5000 on the host machine to port 80 on the guest
  config.vm.network :forwarded_port, guest: 80, host: 4000

  # Map the repository folder to /var/www/html/express as well as /vagrant
  config.vm.synced_folder "./", "/var/www/html/express"

  # Use Puppet to provision our virtual machine
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "vagrant/manifests"
    puppet.manifest_file  = "init.pp"
  end
end