# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty32"

  # Map port 5000 on the host machine to port 80 on the guest (WordPress)
  config.vm.network :forwarded_port, guest: 80, host: 5000

  # Map port 5001 on the host machine to port 8000 on the guest (phpMyAdmin)
  config.vm.network :forwarded_port, guest: 8000, host: 5001

  # Assign a private IP address to the guest
  config.vm.network "private_network", ip: "10.14.14.14"

  # Map the repository folder to /var/www/html/wordpress as well as /vagrant
  config.vm.synced_folder "./", "/var/www/html/wordpress"

  # Customize the guest
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "WordPress Dev"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

  # Fix "stdin: is not a tty" message
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Needs to be run before the main puppet manifest
  config.vm.provision :shell, :inline => "sudo apt-get update"

  # Use Puppet to provision our virtual machine
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "vagrant/manifests"
    puppet.manifest_file  = "init.pp"
  end
end
