# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network :forwarded_port, guest: 80, host: 19000   # Varnish
  config.vm.network :forwarded_port, guest: 8000, host: 19001 # Nginx backend
  config.vm.network :forwarded_port, guest: 6085, host: 19002 # Varnish agent 2

  # Customize the guest
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "Varnish 4 Dev"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

  # Provision the VM using Puppet
  config.vm.provision :puppet, run: "always" do |puppet|
    puppet.manifests_path = "provisioning"
    puppet.manifest_file  = "vagrant.pp"
  end

  # Fix "stdin: is not a tty" message
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
end
